# Generated by Django 5.0.6 on 2024-06-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pzzle',
            name='age',
            field=models.IntegerField(verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='count',
            field=models.IntegerField(verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='detail',
            field=models.IntegerField(verbose_name='деталей'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='material',
            field=models.CharField(max_length=30, verbose_name='материал'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='name',
            field=models.CharField(max_length=30, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='pzzle',
            name='style',
            field=models.CharField(max_length=30, verbose_name='стиль'),
        ),
    ]
