# Generated by Django 5.0.6 on 2024-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_pzzle_age_alter_pzzle_count_alter_pzzle_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzzle',
            name='pic',
            field=models.ImageField(blank=True, upload_to='app1/static/img'),
        ),
    ]
