# Generated by Django 5.0.6 on 2024-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pzzle_producer'),
    ]

    operations = [
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=30)),
                ('size_height', models.CharField(max_length=30)),
                ('size_width', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
