# Generated by Django 5.0.6 on 2024-06-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_size_delete_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='pzzle',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.size'),
        ),
    ]
